### PR TITLE
Refactor: Migrate to Minitest 5 and ActiveSupport 5 

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
### Context 
This PR updates some gems versions to newer versions, which will help the support ruby >= 3 work   (see https://github.com/ncbo/bioportal-project/issues/275) 

### Changes 

* Migrate `minitest` to version 5 and add `minitest-hooks` to reproduce the existent before_suites and after_suites behavior no more existent in `minitest` 5 
* Upgrade `activeSupport` to version 5
* Unpin `Bigdecimal` and `oj` gems

### CODE REVIEW

**Comment by alexskr** [comment]
relates to https://github.com/ncbo/ontologies_api/issues/113

**Comment by alexskr** [comment]
unit tests are failing in GitHub actions for AG but are passing locally.  Is this ready for the review?

**Comment by syphax-bouazzouni** [comment]
> unit tests are failing in GitHub actions for AG but are passing locally. Is this ready for the review?

The test failing is related to the order of tests. If you run the test locally with the same seed, you should the see the same errors.
image
 
Didn't figure out, what is the cause for now.

**Comment by alexskr** [comment]
I wasn't able to reproduce this on my end with the seed that was failing.   Is it failing for you when you run it locally?

**Comment by jvendetti** [comment]
@alexskr - this is in response to a question you asked above:

>  Is this ready for the review?

Syphax submitted this pull request in response to [a ticket](https://github.com/ncbo/ontologies_api/issues/142) I recently entered that details the difficulties of trying to work with the `ontologies_api` project in Ruby 3, due to several outdated dependencies. Please note that he characterized the pull request as a starting point in [this comment](https://github.com/ncbo/ontologies_api/issues/142#issuecomment-2009002244):

> ... just be aware, that I have not yet found time, to deploy it fully on our side, so take this PR with precaution, but I think at least it is a good starting point to the Minitest migration.

Since Syphax was kind enough to submit a starting point for us, I think the onus should be on the BioPortal team to make a good faith effort to evaluate the code and try working out any issues on our end before asking for his assistance with troubleshooting.

**Comment by alexskr** [comment]
my intention is not to rush anyone but to state that the unit tests are passing on my end as far as I can tell.

**Comment by jvendetti** [comment]
It wasn't my intention to imply that you're rushing anyone. Rather, I wanted to make sure Syphax's comments from the other ticket were included here. For anyone looking at this pull request, I thought it should be clear that this hasn't been fully deployed on their side, and may require some extra attention to get it fully integrated on our side.

**Pull request merged**
