### PR TITLE
Feature: Add the slices CRUD endpoints

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
Forked from #19 

This PR adds the following endpoints : 
- Create slice `POST  https://data.bioontology.org/sclices`
- Get slice details `GET https://data.bioontology.org/sclices/:slice_id`
- Update slide info `POST https://data.bioontology.org/sclices/:slice_id `
- Delete a slice `DELETE https://data.bioontology.org/sclices/:slice_id` 

Our long-term vision behind slices can be found [here](https://github.com/agroportal/project-management/issues/35#issuecomment-1209693008); In brief gives the possibility the users to create their slices, with their ontologies, colors, and logo, .... Making Ontoportal a sort a Portal provider for people that don't want or don't have the resources to deploy there own instances (and with portal federation, everything will be also connected).

The biggest blocker here, about the slice features is that we can't can't dynamically create a DSN configuration for each of the slices created by a user.

### CODE REVIEW

**Comment by alexskr** [comment]
should slice creation/update be restricted to users with administrative privileges?

**Comment by alexskr** [comment]
> The biggest blocker here, about the slice features is that we can't can't dynamically create a DSN configuration for each of the slices created by a user.
it can be done with wildcard subdomains.

**Comment by syphax-bouazzouni** [comment]
> Should slice creation/update be restricted to users with administrative privileges?
Now that I have checked again my own code (a year) later, it is true that with this version anyone can create and delete a slice there is no ownership in the current model. 

For now, I added a security check on each of the slice write operations.   That prevents no admin users from editing them.
````
 error 403, "Access denied" unless current_user && current_user.admin?
```

**Comment by alexskr** [comment]
@syphax-bouazzouni, thanks for adding security check.
Would you please add necessary unit tests for the new functionality.

**Comment by alexskr** [comment]
it would also be a good idea to restrict the use of underscores  (_) in the slice names.  
Underscores are generally allowed in subdomain names according to the DNS specification. However, it's important to note that while they are technically allowed, they may not be supported or accepted by all DNS servers, web browsers, and software applications.

**Comment by syphax-bouazzouni** [comment]
> @syphax-bouazzouni, thanks for adding security check. Would you please add necessary unit tests for the new functionality.

Added  here https://github.com/ncbo/ontologies_api/pull/87/commits/6dc238dd96b0da8b035737a0f173a63de3f6c289



> it would also be a good idea to restrict the use of underscores (_) in the slice names. Underscores are generally allowed in subdomain names according to the DNS specification. However, it's important to note that while they are technically allowed, they may not be supported or accepted by all DNS servers, web browsers, software applications and certificate authorities.

Added https://github.com/ncbo/ontologies_linked_data/pull/176

**Comment by alexskr** [comment]
@syphax-bouazzouni, Looks great!

**Comment by mdorf** [comment]
@syphax-bouazzouni, we want to merge this PR, but it contains a dependency on a specific branch of `'ontoportal-lirmm/ontologies_linked_data'`:
```
gem 'ontologies_linked_data', github: 'ontoportal-lirmm/ontologies_linked_data', branch: 'pr/feature/extend-slice-acronym-validator' 
```
We definitely don't want to add this dependency to codebase. This PR doesn't make it clear what functionality/code exactly it requires from that `'ontoportal-lirmm/ontologies_linked_data'` branch. Is there another PR that contains that functionality?

**Comment by mdorf** [comment]
If we merge the PR ncbo/ontologies_linked_data#176, can we then remove the dependency on ontoportal-lirmm, or are there other changes that need to be merged first?

**Comment by syphax-bouazzouni** [comment]
> If we merge the PR [ncbo/ontologies_linked_data#176](https://github.com/ncbo/ontologies_linked_data/pull/176), can we then remove the dependency on ontoportal-lirmm, or are there other changes that need to be merged first?

Yes, this change in the Gemfile, was just to pass the tests.

**Pull request merged**
